// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/math_service.proto

#include "voltha_protos/math_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace async_grpc {
namespace proto {
class GetSumRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSumRequest>
      _instance;
} _GetSumRequest_default_instance_;
class GetSumResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSumResponse>
      _instance;
} _GetSumResponse_default_instance_;
class GetSquareRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSquareRequest>
      _instance;
} _GetSquareRequest_default_instance_;
class GetSquareResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSquareResponse>
      _instance;
} _GetSquareResponse_default_instance_;
class GetEchoRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetEchoRequest>
      _instance;
} _GetEchoRequest_default_instance_;
class GetEchoResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetEchoResponse>
      _instance;
} _GetEchoResponse_default_instance_;
class GetSequenceRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSequenceRequest>
      _instance;
} _GetSequenceRequest_default_instance_;
class GetSequenceResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSequenceResponse>
      _instance;
} _GetSequenceResponse_default_instance_;
}  // namespace proto
}  // namespace async_grpc
namespace protobuf_voltha_5fprotos_2fmath_5fservice_2eproto {
void InitDefaultsGetSumRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSumRequest_default_instance_;
    new (ptr) ::async_grpc::proto::GetSumRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSumRequest::InitAsDefaultInstance();
}

void InitDefaultsGetSumRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSumRequestImpl);
}

void InitDefaultsGetSumResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSumResponse_default_instance_;
    new (ptr) ::async_grpc::proto::GetSumResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSumResponse::InitAsDefaultInstance();
}

void InitDefaultsGetSumResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSumResponseImpl);
}

void InitDefaultsGetSquareRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSquareRequest_default_instance_;
    new (ptr) ::async_grpc::proto::GetSquareRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSquareRequest::InitAsDefaultInstance();
}

void InitDefaultsGetSquareRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSquareRequestImpl);
}

void InitDefaultsGetSquareResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSquareResponse_default_instance_;
    new (ptr) ::async_grpc::proto::GetSquareResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSquareResponse::InitAsDefaultInstance();
}

void InitDefaultsGetSquareResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSquareResponseImpl);
}

void InitDefaultsGetEchoRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetEchoRequest_default_instance_;
    new (ptr) ::async_grpc::proto::GetEchoRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetEchoRequest::InitAsDefaultInstance();
}

void InitDefaultsGetEchoRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetEchoRequestImpl);
}

void InitDefaultsGetEchoResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetEchoResponse_default_instance_;
    new (ptr) ::async_grpc::proto::GetEchoResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetEchoResponse::InitAsDefaultInstance();
}

void InitDefaultsGetEchoResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetEchoResponseImpl);
}

void InitDefaultsGetSequenceRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSequenceRequest_default_instance_;
    new (ptr) ::async_grpc::proto::GetSequenceRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSequenceRequest::InitAsDefaultInstance();
}

void InitDefaultsGetSequenceRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSequenceRequestImpl);
}

void InitDefaultsGetSequenceResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::async_grpc::proto::_GetSequenceResponse_default_instance_;
    new (ptr) ::async_grpc::proto::GetSequenceResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::async_grpc::proto::GetSequenceResponse::InitAsDefaultInstance();
}

void InitDefaultsGetSequenceResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetSequenceResponseImpl);
}

::google::protobuf::Metadata file_level_metadata[8];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSumRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSumRequest, input_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSumResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSumResponse, output_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSquareRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSquareRequest, input_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSquareResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSquareResponse, output_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetEchoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetEchoRequest, input_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetEchoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetEchoResponse, output_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSequenceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSequenceRequest, input_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSequenceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::async_grpc::proto::GetSequenceResponse, output_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::async_grpc::proto::GetSumRequest)},
  { 6, -1, sizeof(::async_grpc::proto::GetSumResponse)},
  { 12, -1, sizeof(::async_grpc::proto::GetSquareRequest)},
  { 18, -1, sizeof(::async_grpc::proto::GetSquareResponse)},
  { 24, -1, sizeof(::async_grpc::proto::GetEchoRequest)},
  { 30, -1, sizeof(::async_grpc::proto::GetEchoResponse)},
  { 36, -1, sizeof(::async_grpc::proto::GetSequenceRequest)},
  { 42, -1, sizeof(::async_grpc::proto::GetSequenceResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSumRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSumResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSquareRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSquareResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetEchoRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetEchoResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSequenceRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::async_grpc::proto::_GetSequenceResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "voltha_protos/math_service.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 8);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n voltha_protos/math_service.proto\022\020asyn"
      "c_grpc.proto\"\036\n\rGetSumRequest\022\r\n\005input\030\001"
      " \001(\005\" \n\016GetSumResponse\022\016\n\006output\030\001 \001(\005\"!"
      "\n\020GetSquareRequest\022\r\n\005input\030\001 \001(\005\"#\n\021Get"
      "SquareResponse\022\016\n\006output\030\001 \001(\005\"\037\n\016GetEch"
      "oRequest\022\r\n\005input\030\001 \001(\005\"!\n\017GetEchoRespon"
      "se\022\016\n\006output\030\001 \001(\005\"#\n\022GetSequenceRequest"
      "\022\r\n\005input\030\001 \001(\005\"%\n\023GetSequenceResponse\022\016"
      "\n\006output\030\001 \001(\0052\261\003\n\004Math\022M\n\006GetSum\022\037.asyn"
      "c_grpc.proto.GetSumRequest\032 .async_grpc."
      "proto.GetSumResponse(\001\022T\n\tGetSquare\022\".as"
      "ync_grpc.proto.GetSquareRequest\032#.async_"
      "grpc.proto.GetSquareResponse\022V\n\rGetRunni"
      "ngSum\022\037.async_grpc.proto.GetSumRequest\032 "
      ".async_grpc.proto.GetSumResponse(\0010\001\022N\n\007"
      "GetEcho\022 .async_grpc.proto.GetEchoReques"
      "t\032!.async_grpc.proto.GetEchoResponse\022\\\n\013"
      "GetSequence\022$.async_grpc.proto.GetSequen"
      "ceRequest\032%.async_grpc.proto.GetSequence"
      "Response0\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 778);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "voltha_protos/math_service.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_voltha_5fprotos_2fmath_5fservice_2eproto
namespace async_grpc {
namespace proto {

// ===================================================================

void GetSumRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSumRequest::kInputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSumRequest::GetSumRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSumRequest)
}
GetSumRequest::GetSumRequest(const GetSumRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  input_ = from.input_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSumRequest)
}

void GetSumRequest::SharedCtor() {
  input_ = 0;
  _cached_size_ = 0;
}

GetSumRequest::~GetSumRequest() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSumRequest)
  SharedDtor();
}

void GetSumRequest::SharedDtor() {
}

void GetSumRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSumRequest::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSumRequest& GetSumRequest::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumRequest();
  return *internal_default_instance();
}

GetSumRequest* GetSumRequest::New(::google::protobuf::Arena* arena) const {
  GetSumRequest* n = new GetSumRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSumRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSumRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_ = 0;
  _internal_metadata_.Clear();
}

bool GetSumRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSumRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 input = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &input_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSumRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSumRequest)
  return false;
#undef DO_
}

void GetSumRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSumRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->input(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSumRequest)
}

::google::protobuf::uint8* GetSumRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSumRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->input(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSumRequest)
  return target;
}

size_t GetSumRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSumRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 input = 1;
  if (this->input() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->input());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSumRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSumRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSumRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSumRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSumRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSumRequest)
    MergeFrom(*source);
  }
}

void GetSumRequest::MergeFrom(const GetSumRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSumRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input() != 0) {
    set_input(from.input());
  }
}

void GetSumRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSumRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSumRequest::CopyFrom(const GetSumRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSumRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSumRequest::IsInitialized() const {
  return true;
}

void GetSumRequest::Swap(GetSumRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSumRequest::InternalSwap(GetSumRequest* other) {
  using std::swap;
  swap(input_, other->input_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSumRequest::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSumResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSumResponse::kOutputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSumResponse::GetSumResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSumResponse)
}
GetSumResponse::GetSumResponse(const GetSumResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_ = from.output_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSumResponse)
}

void GetSumResponse::SharedCtor() {
  output_ = 0;
  _cached_size_ = 0;
}

GetSumResponse::~GetSumResponse() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSumResponse)
  SharedDtor();
}

void GetSumResponse::SharedDtor() {
}

void GetSumResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSumResponse::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSumResponse& GetSumResponse::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumResponse();
  return *internal_default_instance();
}

GetSumResponse* GetSumResponse::New(::google::protobuf::Arena* arena) const {
  GetSumResponse* n = new GetSumResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSumResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSumResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  output_ = 0;
  _internal_metadata_.Clear();
}

bool GetSumResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSumResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &output_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSumResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSumResponse)
  return false;
#undef DO_
}

void GetSumResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSumResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->output(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSumResponse)
}

::google::protobuf::uint8* GetSumResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSumResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->output(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSumResponse)
  return target;
}

size_t GetSumResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSumResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 output = 1;
  if (this->output() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->output());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSumResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSumResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSumResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSumResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSumResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSumResponse)
    MergeFrom(*source);
  }
}

void GetSumResponse::MergeFrom(const GetSumResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSumResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.output() != 0) {
    set_output(from.output());
  }
}

void GetSumResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSumResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSumResponse::CopyFrom(const GetSumResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSumResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSumResponse::IsInitialized() const {
  return true;
}

void GetSumResponse::Swap(GetSumResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSumResponse::InternalSwap(GetSumResponse* other) {
  using std::swap;
  swap(output_, other->output_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSumResponse::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSquareRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSquareRequest::kInputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSquareRequest::GetSquareRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSquareRequest)
}
GetSquareRequest::GetSquareRequest(const GetSquareRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  input_ = from.input_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSquareRequest)
}

void GetSquareRequest::SharedCtor() {
  input_ = 0;
  _cached_size_ = 0;
}

GetSquareRequest::~GetSquareRequest() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSquareRequest)
  SharedDtor();
}

void GetSquareRequest::SharedDtor() {
}

void GetSquareRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSquareRequest::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSquareRequest& GetSquareRequest::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareRequest();
  return *internal_default_instance();
}

GetSquareRequest* GetSquareRequest::New(::google::protobuf::Arena* arena) const {
  GetSquareRequest* n = new GetSquareRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSquareRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSquareRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_ = 0;
  _internal_metadata_.Clear();
}

bool GetSquareRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSquareRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 input = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &input_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSquareRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSquareRequest)
  return false;
#undef DO_
}

void GetSquareRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSquareRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->input(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSquareRequest)
}

::google::protobuf::uint8* GetSquareRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSquareRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->input(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSquareRequest)
  return target;
}

size_t GetSquareRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSquareRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 input = 1;
  if (this->input() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->input());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSquareRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSquareRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSquareRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSquareRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSquareRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSquareRequest)
    MergeFrom(*source);
  }
}

void GetSquareRequest::MergeFrom(const GetSquareRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSquareRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input() != 0) {
    set_input(from.input());
  }
}

void GetSquareRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSquareRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSquareRequest::CopyFrom(const GetSquareRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSquareRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSquareRequest::IsInitialized() const {
  return true;
}

void GetSquareRequest::Swap(GetSquareRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSquareRequest::InternalSwap(GetSquareRequest* other) {
  using std::swap;
  swap(input_, other->input_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSquareRequest::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSquareResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSquareResponse::kOutputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSquareResponse::GetSquareResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSquareResponse)
}
GetSquareResponse::GetSquareResponse(const GetSquareResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_ = from.output_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSquareResponse)
}

void GetSquareResponse::SharedCtor() {
  output_ = 0;
  _cached_size_ = 0;
}

GetSquareResponse::~GetSquareResponse() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSquareResponse)
  SharedDtor();
}

void GetSquareResponse::SharedDtor() {
}

void GetSquareResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSquareResponse::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSquareResponse& GetSquareResponse::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareResponse();
  return *internal_default_instance();
}

GetSquareResponse* GetSquareResponse::New(::google::protobuf::Arena* arena) const {
  GetSquareResponse* n = new GetSquareResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSquareResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSquareResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  output_ = 0;
  _internal_metadata_.Clear();
}

bool GetSquareResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSquareResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &output_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSquareResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSquareResponse)
  return false;
#undef DO_
}

void GetSquareResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSquareResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->output(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSquareResponse)
}

::google::protobuf::uint8* GetSquareResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSquareResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->output(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSquareResponse)
  return target;
}

size_t GetSquareResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSquareResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 output = 1;
  if (this->output() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->output());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSquareResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSquareResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSquareResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSquareResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSquareResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSquareResponse)
    MergeFrom(*source);
  }
}

void GetSquareResponse::MergeFrom(const GetSquareResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSquareResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.output() != 0) {
    set_output(from.output());
  }
}

void GetSquareResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSquareResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSquareResponse::CopyFrom(const GetSquareResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSquareResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSquareResponse::IsInitialized() const {
  return true;
}

void GetSquareResponse::Swap(GetSquareResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSquareResponse::InternalSwap(GetSquareResponse* other) {
  using std::swap;
  swap(output_, other->output_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSquareResponse::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetEchoRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetEchoRequest::kInputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetEchoRequest::GetEchoRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetEchoRequest)
}
GetEchoRequest::GetEchoRequest(const GetEchoRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  input_ = from.input_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetEchoRequest)
}

void GetEchoRequest::SharedCtor() {
  input_ = 0;
  _cached_size_ = 0;
}

GetEchoRequest::~GetEchoRequest() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetEchoRequest)
  SharedDtor();
}

void GetEchoRequest::SharedDtor() {
}

void GetEchoRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetEchoRequest::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetEchoRequest& GetEchoRequest::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoRequest();
  return *internal_default_instance();
}

GetEchoRequest* GetEchoRequest::New(::google::protobuf::Arena* arena) const {
  GetEchoRequest* n = new GetEchoRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetEchoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetEchoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_ = 0;
  _internal_metadata_.Clear();
}

bool GetEchoRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetEchoRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 input = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &input_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetEchoRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetEchoRequest)
  return false;
#undef DO_
}

void GetEchoRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetEchoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->input(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetEchoRequest)
}

::google::protobuf::uint8* GetEchoRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetEchoRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->input(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetEchoRequest)
  return target;
}

size_t GetEchoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetEchoRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 input = 1;
  if (this->input() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->input());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetEchoRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetEchoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetEchoRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetEchoRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetEchoRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetEchoRequest)
    MergeFrom(*source);
  }
}

void GetEchoRequest::MergeFrom(const GetEchoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetEchoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input() != 0) {
    set_input(from.input());
  }
}

void GetEchoRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetEchoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetEchoRequest::CopyFrom(const GetEchoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetEchoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetEchoRequest::IsInitialized() const {
  return true;
}

void GetEchoRequest::Swap(GetEchoRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetEchoRequest::InternalSwap(GetEchoRequest* other) {
  using std::swap;
  swap(input_, other->input_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetEchoRequest::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetEchoResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetEchoResponse::kOutputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetEchoResponse::GetEchoResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetEchoResponse)
}
GetEchoResponse::GetEchoResponse(const GetEchoResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_ = from.output_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetEchoResponse)
}

void GetEchoResponse::SharedCtor() {
  output_ = 0;
  _cached_size_ = 0;
}

GetEchoResponse::~GetEchoResponse() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetEchoResponse)
  SharedDtor();
}

void GetEchoResponse::SharedDtor() {
}

void GetEchoResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetEchoResponse::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetEchoResponse& GetEchoResponse::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoResponse();
  return *internal_default_instance();
}

GetEchoResponse* GetEchoResponse::New(::google::protobuf::Arena* arena) const {
  GetEchoResponse* n = new GetEchoResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetEchoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetEchoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  output_ = 0;
  _internal_metadata_.Clear();
}

bool GetEchoResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetEchoResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &output_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetEchoResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetEchoResponse)
  return false;
#undef DO_
}

void GetEchoResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetEchoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->output(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetEchoResponse)
}

::google::protobuf::uint8* GetEchoResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetEchoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->output(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetEchoResponse)
  return target;
}

size_t GetEchoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetEchoResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 output = 1;
  if (this->output() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->output());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetEchoResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetEchoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetEchoResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetEchoResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetEchoResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetEchoResponse)
    MergeFrom(*source);
  }
}

void GetEchoResponse::MergeFrom(const GetEchoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetEchoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.output() != 0) {
    set_output(from.output());
  }
}

void GetEchoResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetEchoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetEchoResponse::CopyFrom(const GetEchoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetEchoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetEchoResponse::IsInitialized() const {
  return true;
}

void GetEchoResponse::Swap(GetEchoResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetEchoResponse::InternalSwap(GetEchoResponse* other) {
  using std::swap;
  swap(output_, other->output_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetEchoResponse::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSequenceRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSequenceRequest::kInputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSequenceRequest::GetSequenceRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSequenceRequest)
}
GetSequenceRequest::GetSequenceRequest(const GetSequenceRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  input_ = from.input_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSequenceRequest)
}

void GetSequenceRequest::SharedCtor() {
  input_ = 0;
  _cached_size_ = 0;
}

GetSequenceRequest::~GetSequenceRequest() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSequenceRequest)
  SharedDtor();
}

void GetSequenceRequest::SharedDtor() {
}

void GetSequenceRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSequenceRequest::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSequenceRequest& GetSequenceRequest::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceRequest();
  return *internal_default_instance();
}

GetSequenceRequest* GetSequenceRequest::New(::google::protobuf::Arena* arena) const {
  GetSequenceRequest* n = new GetSequenceRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSequenceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSequenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_ = 0;
  _internal_metadata_.Clear();
}

bool GetSequenceRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSequenceRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 input = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &input_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSequenceRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSequenceRequest)
  return false;
#undef DO_
}

void GetSequenceRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSequenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->input(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSequenceRequest)
}

::google::protobuf::uint8* GetSequenceRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSequenceRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 input = 1;
  if (this->input() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->input(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSequenceRequest)
  return target;
}

size_t GetSequenceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSequenceRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 input = 1;
  if (this->input() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->input());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSequenceRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSequenceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSequenceRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSequenceRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSequenceRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSequenceRequest)
    MergeFrom(*source);
  }
}

void GetSequenceRequest::MergeFrom(const GetSequenceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSequenceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input() != 0) {
    set_input(from.input());
  }
}

void GetSequenceRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSequenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSequenceRequest::CopyFrom(const GetSequenceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSequenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSequenceRequest::IsInitialized() const {
  return true;
}

void GetSequenceRequest::Swap(GetSequenceRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSequenceRequest::InternalSwap(GetSequenceRequest* other) {
  using std::swap;
  swap(input_, other->input_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSequenceRequest::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSequenceResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSequenceResponse::kOutputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSequenceResponse::GetSequenceResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:async_grpc.proto.GetSequenceResponse)
}
GetSequenceResponse::GetSequenceResponse(const GetSequenceResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_ = from.output_;
  // @@protoc_insertion_point(copy_constructor:async_grpc.proto.GetSequenceResponse)
}

void GetSequenceResponse::SharedCtor() {
  output_ = 0;
  _cached_size_ = 0;
}

GetSequenceResponse::~GetSequenceResponse() {
  // @@protoc_insertion_point(destructor:async_grpc.proto.GetSequenceResponse)
  SharedDtor();
}

void GetSequenceResponse::SharedDtor() {
}

void GetSequenceResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetSequenceResponse::descriptor() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSequenceResponse& GetSequenceResponse::default_instance() {
  ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceResponse();
  return *internal_default_instance();
}

GetSequenceResponse* GetSequenceResponse::New(::google::protobuf::Arena* arena) const {
  GetSequenceResponse* n = new GetSequenceResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetSequenceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:async_grpc.proto.GetSequenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  output_ = 0;
  _internal_metadata_.Clear();
}

bool GetSequenceResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:async_grpc.proto.GetSequenceResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &output_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:async_grpc.proto.GetSequenceResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:async_grpc.proto.GetSequenceResponse)
  return false;
#undef DO_
}

void GetSequenceResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:async_grpc.proto.GetSequenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->output(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:async_grpc.proto.GetSequenceResponse)
}

::google::protobuf::uint8* GetSequenceResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:async_grpc.proto.GetSequenceResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 output = 1;
  if (this->output() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->output(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:async_grpc.proto.GetSequenceResponse)
  return target;
}

size_t GetSequenceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:async_grpc.proto.GetSequenceResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 output = 1;
  if (this->output() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->output());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetSequenceResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:async_grpc.proto.GetSequenceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSequenceResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSequenceResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:async_grpc.proto.GetSequenceResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:async_grpc.proto.GetSequenceResponse)
    MergeFrom(*source);
  }
}

void GetSequenceResponse::MergeFrom(const GetSequenceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:async_grpc.proto.GetSequenceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.output() != 0) {
    set_output(from.output());
  }
}

void GetSequenceResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:async_grpc.proto.GetSequenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSequenceResponse::CopyFrom(const GetSequenceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:async_grpc.proto.GetSequenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSequenceResponse::IsInitialized() const {
  return true;
}

void GetSequenceResponse::Swap(GetSequenceResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSequenceResponse::InternalSwap(GetSequenceResponse* other) {
  using std::swap;
  swap(output_, other->output_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetSequenceResponse::GetMetadata() const {
  protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace async_grpc

// @@protoc_insertion_point(global_scope)
