// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/math_service.proto

#ifndef PROTOBUF_voltha_5fprotos_2fmath_5fservice_2eproto__INCLUDED
#define PROTOBUF_voltha_5fprotos_2fmath_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_voltha_5fprotos_2fmath_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGetSumRequestImpl();
void InitDefaultsGetSumRequest();
void InitDefaultsGetSumResponseImpl();
void InitDefaultsGetSumResponse();
void InitDefaultsGetSquareRequestImpl();
void InitDefaultsGetSquareRequest();
void InitDefaultsGetSquareResponseImpl();
void InitDefaultsGetSquareResponse();
void InitDefaultsGetEchoRequestImpl();
void InitDefaultsGetEchoRequest();
void InitDefaultsGetEchoResponseImpl();
void InitDefaultsGetEchoResponse();
void InitDefaultsGetSequenceRequestImpl();
void InitDefaultsGetSequenceRequest();
void InitDefaultsGetSequenceResponseImpl();
void InitDefaultsGetSequenceResponse();
inline void InitDefaults() {
  InitDefaultsGetSumRequest();
  InitDefaultsGetSumResponse();
  InitDefaultsGetSquareRequest();
  InitDefaultsGetSquareResponse();
  InitDefaultsGetEchoRequest();
  InitDefaultsGetEchoResponse();
  InitDefaultsGetSequenceRequest();
  InitDefaultsGetSequenceResponse();
}
}  // namespace protobuf_voltha_5fprotos_2fmath_5fservice_2eproto
namespace async_grpc {
namespace proto {
class GetEchoRequest;
class GetEchoRequestDefaultTypeInternal;
extern GetEchoRequestDefaultTypeInternal _GetEchoRequest_default_instance_;
class GetEchoResponse;
class GetEchoResponseDefaultTypeInternal;
extern GetEchoResponseDefaultTypeInternal _GetEchoResponse_default_instance_;
class GetSequenceRequest;
class GetSequenceRequestDefaultTypeInternal;
extern GetSequenceRequestDefaultTypeInternal _GetSequenceRequest_default_instance_;
class GetSequenceResponse;
class GetSequenceResponseDefaultTypeInternal;
extern GetSequenceResponseDefaultTypeInternal _GetSequenceResponse_default_instance_;
class GetSquareRequest;
class GetSquareRequestDefaultTypeInternal;
extern GetSquareRequestDefaultTypeInternal _GetSquareRequest_default_instance_;
class GetSquareResponse;
class GetSquareResponseDefaultTypeInternal;
extern GetSquareResponseDefaultTypeInternal _GetSquareResponse_default_instance_;
class GetSumRequest;
class GetSumRequestDefaultTypeInternal;
extern GetSumRequestDefaultTypeInternal _GetSumRequest_default_instance_;
class GetSumResponse;
class GetSumResponseDefaultTypeInternal;
extern GetSumResponseDefaultTypeInternal _GetSumResponse_default_instance_;
}  // namespace proto
}  // namespace async_grpc
namespace async_grpc {
namespace proto {

// ===================================================================

class GetSumRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSumRequest) */ {
 public:
  GetSumRequest();
  virtual ~GetSumRequest();

  GetSumRequest(const GetSumRequest& from);

  inline GetSumRequest& operator=(const GetSumRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSumRequest(GetSumRequest&& from) noexcept
    : GetSumRequest() {
    *this = ::std::move(from);
  }

  inline GetSumRequest& operator=(GetSumRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSumRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSumRequest* internal_default_instance() {
    return reinterpret_cast<const GetSumRequest*>(
               &_GetSumRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GetSumRequest* other);
  friend void swap(GetSumRequest& a, GetSumRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSumRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSumRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSumRequest& from);
  void MergeFrom(const GetSumRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSumRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 input = 1;
  void clear_input();
  static const int kInputFieldNumber = 1;
  ::google::protobuf::int32 input() const;
  void set_input(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSumRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 input_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumRequestImpl();
};
// -------------------------------------------------------------------

class GetSumResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSumResponse) */ {
 public:
  GetSumResponse();
  virtual ~GetSumResponse();

  GetSumResponse(const GetSumResponse& from);

  inline GetSumResponse& operator=(const GetSumResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSumResponse(GetSumResponse&& from) noexcept
    : GetSumResponse() {
    *this = ::std::move(from);
  }

  inline GetSumResponse& operator=(GetSumResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSumResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSumResponse* internal_default_instance() {
    return reinterpret_cast<const GetSumResponse*>(
               &_GetSumResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GetSumResponse* other);
  friend void swap(GetSumResponse& a, GetSumResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSumResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSumResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSumResponse& from);
  void MergeFrom(const GetSumResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSumResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 output = 1;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  ::google::protobuf::int32 output() const;
  void set_output(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSumResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 output_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSumResponseImpl();
};
// -------------------------------------------------------------------

class GetSquareRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSquareRequest) */ {
 public:
  GetSquareRequest();
  virtual ~GetSquareRequest();

  GetSquareRequest(const GetSquareRequest& from);

  inline GetSquareRequest& operator=(const GetSquareRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSquareRequest(GetSquareRequest&& from) noexcept
    : GetSquareRequest() {
    *this = ::std::move(from);
  }

  inline GetSquareRequest& operator=(GetSquareRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSquareRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSquareRequest* internal_default_instance() {
    return reinterpret_cast<const GetSquareRequest*>(
               &_GetSquareRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetSquareRequest* other);
  friend void swap(GetSquareRequest& a, GetSquareRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSquareRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSquareRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSquareRequest& from);
  void MergeFrom(const GetSquareRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSquareRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 input = 1;
  void clear_input();
  static const int kInputFieldNumber = 1;
  ::google::protobuf::int32 input() const;
  void set_input(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSquareRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 input_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareRequestImpl();
};
// -------------------------------------------------------------------

class GetSquareResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSquareResponse) */ {
 public:
  GetSquareResponse();
  virtual ~GetSquareResponse();

  GetSquareResponse(const GetSquareResponse& from);

  inline GetSquareResponse& operator=(const GetSquareResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSquareResponse(GetSquareResponse&& from) noexcept
    : GetSquareResponse() {
    *this = ::std::move(from);
  }

  inline GetSquareResponse& operator=(GetSquareResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSquareResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSquareResponse* internal_default_instance() {
    return reinterpret_cast<const GetSquareResponse*>(
               &_GetSquareResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GetSquareResponse* other);
  friend void swap(GetSquareResponse& a, GetSquareResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSquareResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSquareResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSquareResponse& from);
  void MergeFrom(const GetSquareResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSquareResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 output = 1;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  ::google::protobuf::int32 output() const;
  void set_output(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSquareResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 output_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSquareResponseImpl();
};
// -------------------------------------------------------------------

class GetEchoRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetEchoRequest) */ {
 public:
  GetEchoRequest();
  virtual ~GetEchoRequest();

  GetEchoRequest(const GetEchoRequest& from);

  inline GetEchoRequest& operator=(const GetEchoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetEchoRequest(GetEchoRequest&& from) noexcept
    : GetEchoRequest() {
    *this = ::std::move(from);
  }

  inline GetEchoRequest& operator=(GetEchoRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetEchoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetEchoRequest* internal_default_instance() {
    return reinterpret_cast<const GetEchoRequest*>(
               &_GetEchoRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(GetEchoRequest* other);
  friend void swap(GetEchoRequest& a, GetEchoRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetEchoRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetEchoRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetEchoRequest& from);
  void MergeFrom(const GetEchoRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetEchoRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 input = 1;
  void clear_input();
  static const int kInputFieldNumber = 1;
  ::google::protobuf::int32 input() const;
  void set_input(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetEchoRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 input_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoRequestImpl();
};
// -------------------------------------------------------------------

class GetEchoResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetEchoResponse) */ {
 public:
  GetEchoResponse();
  virtual ~GetEchoResponse();

  GetEchoResponse(const GetEchoResponse& from);

  inline GetEchoResponse& operator=(const GetEchoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetEchoResponse(GetEchoResponse&& from) noexcept
    : GetEchoResponse() {
    *this = ::std::move(from);
  }

  inline GetEchoResponse& operator=(GetEchoResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetEchoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetEchoResponse* internal_default_instance() {
    return reinterpret_cast<const GetEchoResponse*>(
               &_GetEchoResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(GetEchoResponse* other);
  friend void swap(GetEchoResponse& a, GetEchoResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetEchoResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetEchoResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetEchoResponse& from);
  void MergeFrom(const GetEchoResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetEchoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 output = 1;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  ::google::protobuf::int32 output() const;
  void set_output(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetEchoResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 output_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetEchoResponseImpl();
};
// -------------------------------------------------------------------

class GetSequenceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSequenceRequest) */ {
 public:
  GetSequenceRequest();
  virtual ~GetSequenceRequest();

  GetSequenceRequest(const GetSequenceRequest& from);

  inline GetSequenceRequest& operator=(const GetSequenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSequenceRequest(GetSequenceRequest&& from) noexcept
    : GetSequenceRequest() {
    *this = ::std::move(from);
  }

  inline GetSequenceRequest& operator=(GetSequenceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSequenceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSequenceRequest* internal_default_instance() {
    return reinterpret_cast<const GetSequenceRequest*>(
               &_GetSequenceRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(GetSequenceRequest* other);
  friend void swap(GetSequenceRequest& a, GetSequenceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSequenceRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSequenceRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSequenceRequest& from);
  void MergeFrom(const GetSequenceRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSequenceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 input = 1;
  void clear_input();
  static const int kInputFieldNumber = 1;
  ::google::protobuf::int32 input() const;
  void set_input(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSequenceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 input_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceRequestImpl();
};
// -------------------------------------------------------------------

class GetSequenceResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:async_grpc.proto.GetSequenceResponse) */ {
 public:
  GetSequenceResponse();
  virtual ~GetSequenceResponse();

  GetSequenceResponse(const GetSequenceResponse& from);

  inline GetSequenceResponse& operator=(const GetSequenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetSequenceResponse(GetSequenceResponse&& from) noexcept
    : GetSequenceResponse() {
    *this = ::std::move(from);
  }

  inline GetSequenceResponse& operator=(GetSequenceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSequenceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSequenceResponse* internal_default_instance() {
    return reinterpret_cast<const GetSequenceResponse*>(
               &_GetSequenceResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(GetSequenceResponse* other);
  friend void swap(GetSequenceResponse& a, GetSequenceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetSequenceResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetSequenceResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetSequenceResponse& from);
  void MergeFrom(const GetSequenceResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetSequenceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 output = 1;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  ::google::protobuf::int32 output() const;
  void set_output(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:async_grpc.proto.GetSequenceResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 output_;
  mutable int _cached_size_;
  friend struct ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::TableStruct;
  friend void ::protobuf_voltha_5fprotos_2fmath_5fservice_2eproto::InitDefaultsGetSequenceResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetSumRequest

// int32 input = 1;
inline void GetSumRequest::clear_input() {
  input_ = 0;
}
inline ::google::protobuf::int32 GetSumRequest::input() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSumRequest.input)
  return input_;
}
inline void GetSumRequest::set_input(::google::protobuf::int32 value) {
  
  input_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSumRequest.input)
}

// -------------------------------------------------------------------

// GetSumResponse

// int32 output = 1;
inline void GetSumResponse::clear_output() {
  output_ = 0;
}
inline ::google::protobuf::int32 GetSumResponse::output() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSumResponse.output)
  return output_;
}
inline void GetSumResponse::set_output(::google::protobuf::int32 value) {
  
  output_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSumResponse.output)
}

// -------------------------------------------------------------------

// GetSquareRequest

// int32 input = 1;
inline void GetSquareRequest::clear_input() {
  input_ = 0;
}
inline ::google::protobuf::int32 GetSquareRequest::input() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSquareRequest.input)
  return input_;
}
inline void GetSquareRequest::set_input(::google::protobuf::int32 value) {
  
  input_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSquareRequest.input)
}

// -------------------------------------------------------------------

// GetSquareResponse

// int32 output = 1;
inline void GetSquareResponse::clear_output() {
  output_ = 0;
}
inline ::google::protobuf::int32 GetSquareResponse::output() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSquareResponse.output)
  return output_;
}
inline void GetSquareResponse::set_output(::google::protobuf::int32 value) {
  
  output_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSquareResponse.output)
}

// -------------------------------------------------------------------

// GetEchoRequest

// int32 input = 1;
inline void GetEchoRequest::clear_input() {
  input_ = 0;
}
inline ::google::protobuf::int32 GetEchoRequest::input() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetEchoRequest.input)
  return input_;
}
inline void GetEchoRequest::set_input(::google::protobuf::int32 value) {
  
  input_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetEchoRequest.input)
}

// -------------------------------------------------------------------

// GetEchoResponse

// int32 output = 1;
inline void GetEchoResponse::clear_output() {
  output_ = 0;
}
inline ::google::protobuf::int32 GetEchoResponse::output() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetEchoResponse.output)
  return output_;
}
inline void GetEchoResponse::set_output(::google::protobuf::int32 value) {
  
  output_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetEchoResponse.output)
}

// -------------------------------------------------------------------

// GetSequenceRequest

// int32 input = 1;
inline void GetSequenceRequest::clear_input() {
  input_ = 0;
}
inline ::google::protobuf::int32 GetSequenceRequest::input() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSequenceRequest.input)
  return input_;
}
inline void GetSequenceRequest::set_input(::google::protobuf::int32 value) {
  
  input_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSequenceRequest.input)
}

// -------------------------------------------------------------------

// GetSequenceResponse

// int32 output = 1;
inline void GetSequenceResponse::clear_output() {
  output_ = 0;
}
inline ::google::protobuf::int32 GetSequenceResponse::output() const {
  // @@protoc_insertion_point(field_get:async_grpc.proto.GetSequenceResponse.output)
  return output_;
}
inline void GetSequenceResponse::set_output(::google::protobuf::int32 value) {
  
  output_ = value;
  // @@protoc_insertion_point(field_set:async_grpc.proto.GetSequenceResponse.output)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace async_grpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_voltha_5fprotos_2fmath_5fservice_2eproto__INCLUDED
